name: cron
on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:

  validate:
    runs-on: ubuntu-latest
    outputs:
      new: ${{ steps.check.outputs.new }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Install depepndencies
        run: sudo apt-get install -y curl jq
      - name: Check new version
        id: check
        run: |
          element_version=`curl -SsL https://api.github.com/repos/vector-im/element-web/releases | jq -r '.[].tag_name' | head -n 1`
          echo "::set-output name=version::${element_version}"
          docker_version=`curl -sSL 'https://registry.hub.docker.com/v2/repositories/bubuntux/element-web/tags' | jq -r '."results"[]["name"] | select(.=="'${element_version}'")'`
          if [ "${element_version}" == "${docker_version}" ]; then
            echo "::set-output name=new::false"
          else
            echo "::set-output name=new::true"
          fi
      - name: Print outputs
        run: echo version=${{steps.check.outputs.version}}  new=${{steps.check.outputs.new}}

  release:
    runs-on: ubuntu-latest
    needs: validate
    if: needs.validate.outputs.new == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: version=${{ needs.validate.outputs.version }}
          push: true
          tags: |
            bubuntux/riot-web:${{ needs.validate.outputs.version }}
            ${{ github.repository }}:${{ needs.validate.outputs.version }}
            ghcr.io/${{ github.repository }}:${{ needs.validate.outputs.version }}

      - name: Push latest
        if: ${{ !contains( needs.validate.outputs.version , 'rc') }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: version=${{ needs.validate.outputs.version }}
          push: true
          tags: |
            bubuntux/riot-web:latest
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
